using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MyProject.Analyzers.Authoring;

[PublicAPI]
public static partial class Extensions
{
    public const string AutoGeneratedHeader =
        """
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Changes to this file may cause incorrect behavior and will be lost if
        //     the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
        """;
    
    private const string ReplaceToken = "//~REPLACE";

    private static HashSet<string> _reservedWords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char", "checked", "class", "const", "continue", "decimal", "default", "delegate", "do", "double", "else", "enum", "event", "explicit", "extern",
        "false", "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit", "in", "int", "interface", "internal", "is", "lock", "long", "namespace", "new", "null", "object", "operator", "out", "override",
        "params", "private", "protected", "public", "readonly", "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string", "struct", "switch", "this", "throw", "true", "try", "typeof", "uint",
        "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
    ];

    public static string EnsureSafeIdentifier(this string s) => $"{s[0].ToString().ToLower()}{s.Remove(0, 1)}";
    public static string ToCamelCase(this string s) => $"{s[0].ToString().ToLower()}{s.Remove(0, 1)}";


    public static string Ident(this object source, int identLevels)
    {
        var lines = source.ToString()?.TrimStart(' ').Split('\n') ?? [];
        var ident = new string(' ', identLevels * 4);
        return string.Join("\n", lines.Select((x, i) => $"""{ (i > 0 ? ident : "") }{x}"""));
    }

    public static string RenderParameters<T>(
        this IEnumerable<T> source,
        Func<T, string> template)
    {
        return Render(source, template, separator: ", ", "(", ")");
    }
    public static string RenderStatements<T>(
        this IEnumerable<T> source,
        Func<T, string> template)
    {
        return Render(source, template, separator: "\n");
    }
    public static string RenderBlock<T>(
        this IEnumerable<T> source,
        Func<T, string> template)
    {
        return Render(source, template, separator: "\n", "{", "}");
    }
    public static string Render<T>(
        this IEnumerable<T> source,
        Func<T, string> template,
        string separator = "",
        string openToken = "",
        string closeToken = "",
        bool renderEmpty = true)
    {

        var renderedItems = source.Select(template).ToArray();
        
        if (!renderEmpty && renderedItems.Length == 0)
            return "";
        
        bool multiline = renderedItems.Any(r => r.Contains('\n'));

        if (multiline)
        {
            var outerIndent = IndentationContext.CurrentIndent;

            using (IndentationContext.Increase())
            {
                var innerRender = IndentationContext.RenderIndented(renderedItems);
                // var innerIndent = IndentationContext.CurrentIndent;
                // var indentedItems = renderedItems
                //     .Select(r => string.Join(Environment.NewLine,
                //         r.Split('\n').Select(l => innerIndent + l.TrimEnd())));

                return $"{outerIndent}{openToken}\n{innerRender}\n{outerIndent}{closeToken}";
            }
        }
        else
        {
            return $"{IndentationContext.CurrentIndent}{openToken}{string.Join(separator, renderedItems)}{closeToken}";
        }
    }


    public static string Render<T>(this IEnumerable<T> source, Func<T, int, string> template, string separator = "")
    {
        return string.Join(separator, source.Select(template));
    }

    public static void RenderSourceFile<T>(this T partialTemplateModel, Func<T, string> renderBody, SourceProductionContext context, bool renderEmpty = false) where T : PartialTypeModel
    {
        var body = renderBody(partialTemplateModel);
        if(!renderEmpty && string.IsNullOrWhiteSpace(body))
            return;
        var sourceCode = partialTemplateModel.RenderPartial(_ => body);
        context.AddSource(partialTemplateModel.FileName, SourceText.From(sourceCode, Encoding.UTF8));
    }
    public static string RenderPartial<T>(this T partialTemplateModel, Func<T, string> renderBody) where T : PartialTypeModel
    {
        var typeDeclarationSyntax = partialTemplateModel.PartialType;
        var root = typeDeclarationSyntax.SyntaxTree.GetRoot();
        var hierarchy = typeDeclarationSyntax.AncestorsAndSelf().ToList();

        root = root.TrackNodes(hierarchy);
        var children = new SyntaxList<MemberDeclarationSyntax>();
        root = new Stripper().Visit(root);
        foreach(var node in hierarchy)
        {
            var currentNode = (MemberDeclarationSyntax)root.GetCurrentNode(node)!;
            var modifiedNode = currentNode;
            if(modifiedNode is TypeDeclarationSyntax typeDeclaration)
            {
                modifiedNode = typeDeclaration
                    .WithBaseList(null)
                    .WithParameterList(null)
                    .WithMembers(children);
                root = root.ReplaceNode(currentNode, modifiedNode);
                children = new SyntaxList<MemberDeclarationSyntax>(modifiedNode);
            }
            if(modifiedNode is BaseNamespaceDeclarationSyntax nsDeclaration)
            {
                modifiedNode = nsDeclaration.WithMembers(children);
                root = root.ReplaceNode(currentNode, modifiedNode);
                break;
            }

            IndentationContext.Increase();
        }
        typeDeclarationSyntax = root.GetCurrentNode(typeDeclarationSyntax)!;
        var strippedTypeDeclaration = typeDeclarationSyntax
            .WithOpenBraceToken(typeDeclarationSyntax.OpenBraceToken
                .WithTrailingTrivia(
                    SyntaxFactory.CarriageReturnLineFeed,
                    SyntaxFactory.Comment(ReplaceToken),
                    SyntaxFactory.CarriageReturnLineFeed))
            .WithCloseBraceToken(typeDeclarationSyntax.CloseBraceToken
                .WithLeadingTrivia(typeDeclarationSyntax.CloseBraceToken.LeadingTrivia.LastOrDefault(x => x.IsKind(SyntaxKind.WhitespaceTrivia))))
            ;
        root = root.ReplaceNode(typeDeclarationSyntax, strippedTypeDeclaration);


        var result = root.ToFullString();
        // using var indentationScope = IndentationContext.Increase();
        var body = renderBody(partialTemplateModel);
        var indentedBody = IndentationContext.RenderIndented(body);
        result = result.Replace(ReplaceToken, indentedBody);
        // result = $"#nullable enable\n{result}";
        IndentationContext.Reset();
        return result;
    }

    /// <summary>
    /// Strips out things that shouldn't be redeclared, like attributes and pragma trivia
    /// </summary>
    private class Stripper : CSharpSyntaxRewriter
    {
        public override SyntaxNode? VisitAttributeList(AttributeListSyntax node)
        {
            return null;
        }

        public override SyntaxToken VisitToken(SyntaxToken token)
        {
            token = token.WithTrailingTrivia(OnlyWhitespaceTrivia(token.TrailingTrivia));
            token = token.WithLeadingTrivia(OnlyWhitespaceTrivia(token.LeadingTrivia));
            return token;
        }

        private SyntaxTriviaList OnlyWhitespaceTrivia(SyntaxTriviaList? trivia)
        {
            trivia ??= new SyntaxTriviaList();
            return new SyntaxTriviaList(trivia.Value.Where(x => x.IsKind(SyntaxKind.EndOfLineTrivia) || x.IsKind(SyntaxKind.WhitespaceTrivia)));
        }
    }
}
